spring:
  profiles:
    # dev:开发环境；test:测试环境；prod:生产环境
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          paths: /**

# PageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql